### ISSUE TITLE
Cryptoswap Third Gen

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/twocrypto-ng#10]
# Background

TricryptoNGWETH is the first optimised implementation of the old 3-coin cryptoswap AMM, allowing native token transfers. Its immediate upgrade (almost a year after its launch) removes some of the features and adds new ones. 

The different implementations of Curve's CryptoSwap invariant AMM are noted in the following:

0. The genesis cryptoswap invariant amm contracts:
a. [tricrypto2 (genesis)](https://github.com/curvefi/curve-crypto-contract/blob/master/contracts/tricrypto/CurveCryptoSwap.vy)
b. [twocrypto (genesis)](https://github.com/curvefi/curve-crypto-contract/blob/master/contracts/two/CurveCryptoSwap2ETH.vy)
1. [TricryptoNGWETH (1st gen)](https://github.com/curvefi/tricrypto-ng/blob/main/contracts/main/CurveTricryptoOptimizedWETH.vy)
2. [TwocryptoNG (second gen)](https://github.com/curvefi/twocrypto-ng/blob/main/contracts/main/CurveTwocryptoOptimized.vy)
3. [TricryptoNG (second gen)](https://github.com/curvefi/tricrypto-ng/blob/main/contracts/main/CurveTricryptoOptimized.vy)

There are significant improvements from the genesis cryptoswap invariant AMM contract to the 1st gen (NG, or next-gen). Gas costs are reduced by half between the genesis and the first gen implementations. This was a labour of love, requiring development work in the compiler, dev tools (titanoboa was built to build tricryptong), coordination with etherscan, coordination with math researchers to optimise math in tricrypto, come up with better cube roots, auditors coming up with their optimisations etc. The optimisations are listed in the following:

1. Replace [Bubble sort](https://github.com/curvefi/curve-crypto-contract/blob/d7d04cd9ae038970e40be850df99de8c1ff7241b/contracts/tricrypto/CurveCryptoMath3.vy#L20) with [dumb sorting](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L845)
2. [Bespoke cube root algorithm that costs 2000 gas on average](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L789). Implemented in [Snekmate](https://github.com/pcaversaccio/snekmate/blob/9f7eec740fcaf8e5d4397fc1cc79d507ff11d613/src/snekmate/utils/Math.vy#L490) as well.
3. Replace [expensive geometric mean](https://github.com/curvefi/curve-crypto-contract/blob/d7d04cd9ae038970e40be850df99de8c1ff7241b/contracts/tricrypto/CurveCryptoMath3.vy#L42) with [simple geometric mean](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L868)
4. Use unsafe math operations wherever it is safe to do so. [Old implementation](https://github.com/curvefi/curve-crypto-contract/blob/d7d04cd9ae038970e40be850df99de8c1ff7241b/contracts/tricrypto/CurveCryptoMath3.vy#L96) -> [new implementation with explanation for why we can do unsafe maths](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L431)
5. Replace [newton_y](https://github.com/curvefi/curve-crypto-contract/blob/d7d04cd9ae038970e40be850df99de8c1ff7241b/contracts/tricrypto/CurveCryptoMath3.vy#L172) for [mathematically verified analytical solution with fallback to newton method for edge cases](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L35).
6. [Bespoke and very cheap calculation of partial derivatives of x w.r.t y, which allows the calculation of state prices](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveCryptoMathOptimized3.vy#L539). This was a contribution from Taynan Richards of ChainSecurity, which [replaced the old and initially proposed version](https://github.com/curvefi/tricrypto-ng/commit/b3350d4b7e92d4e12720584b2d1aeb1d74b5a99f).
7. Introduce [Blueprint contracts!](https://eips.ethereum.org/EIPS/eip-5202). This allowed factory deployed contracts to have immutables, since blueprint contracts are not like minimal proxies where immutables are not possible whatsoever. The verification pipeline of blueprint-deployed contracts still needs to be fixed. Still, when it was first deployed, it was only possible to verify the contract when Etherscan added features to read the first few bytes of the bytecode and classify the contract as a blueprint.

The implementation of state prices allowed the creation of very good oracles that power today's curve stablecoin. State prices, as opposed to last traded prices (the widely prevalent industry standard), significantly reduce the impact of price manipulation.

Cryptoswap (like everything Curve has) is an ongoing process of improvement. The features added in the second iteration of NG are simply features that come out of a natural progression of improving contracts after user feedback, experiences with speaking to auditors, etc. No known vulnerabilities in the first NG implementation prompted the second iteration of cryptoswap NG contracts.

Some of the features removed from the first gen (in the second-gen) are (not an exhaustive list):

1. [Native token transfers](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L394)
2. [Gulping of tokens (i.e. when the `self.balances` can be updated with a read of `coin.balanceOf(self)`).](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L1193)
3. [exchange_extended, which is exchanging after calling an external callback first).](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L477)
4. [Admin fees collected in LP tokens.](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L1223)
5. [exposed claim_admin_fees](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L786)
6. [commit-apply scheme for parameters](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L2033). New version applies parameters simply [which is quicker to do](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1994) (in one tx after governance approves).

The second-gen adds several new features including:

1. [An xcp oracle to measure the amount of liquidity in the pool](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1705)
2. [fees are collected in individual tokens and not lp tokens.](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1216)
3. [Claiming individual tokens means LP token supply does not go up](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1173)
4. stricter conditions to claiming fees
a. [claim sparingly](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1116)
b. [do not claim if virtual price goes below 1e18](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L1182)
5. [exchange_received](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimized.vy#L409): swap tokens donated to the pool.The advantage of the new implementation is that if tokens in the pool are rebasing, there is no `self.balances[i] = coins[i].balanceOf(self)` in the `self._claim_admin_fees()` method [like the old contract does](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L1197)

With that in mind, there are new features and more improvements that Cryptoswap contracts could accommodate.

# Improvements Suggested

## 1. Rebasing token support

The second-gen cryptoswap NG contracts do not gulp rebases: if the amm contract holds rebasing tokens, the rebases are not absorbed by the pool contract and are simply available as: `rebase_balance[i] = coins[i].balanceOf(self) - self.balances[i]`. These could be recovered by the LPs somehow and added to their LP token share. This is something to consider: can we add support for pairs like `stETH <> USDM` where both tokens in the pool are rebasing and are very tightly pegged to their underlying collateral's value (at least historically as of writing this feature)?

## 2. Boost

Cryptoswap invariant AMMs take half the earned profits to rebalance liquidity closer to the exponential moving average prices. This means, if the pool had some form of capability to accept donations to inflate its profits, it could absorb these donated profits to rebalance and deepen liquidity significantly. This is even more effective in pools where the tokens do not have significant volatility but are not volatile pairs (e.g., USD <> EUR forex markets, which are generally very deep).

The ability to donate was discontinued in the second generation since the removal of the [`gulp`](https://github.com/curvefi/tricrypto-ng/blob/33707fc8b84e08786acf184fcfdb744eb4657a99/contracts/main/CurveTricryptoOptimizedWETH.vy#L1193).

The idea would be to 
a. Donate to the pool contract safely and not manipulate prices in any direction
b. call tweak_price
c. Donated profits should not go into user positions, and only be used for amm rebalancing.

This is quite tricky to achieve but increases flexibility and utility of these AMM contracts.

# Task List

- [ ] Add rebasing token support
- [ ] Add boost
- [ ] Audit
- [ ] deploy implementations to factories across all chains.
- [ ] curve-api to track the implementation
- [ ] curve-js to allow deploying rebasing and boost supported implementation
- [ ] curve-js to onboard the new interface so it can be displayed in the frontend
- [ ] curve-frontend to onboard the new implementation in pool deployment
- [ ] curve-frontend to onboard pool pages for the new implementation.

**Comment by AlbertoCentonze** [comment]
We should look for a better name for boost since it can create some confusion with the gauges boost.

Are we sure that there is enough demand for the actual rebase feature? Let's estimate the percentage of protocols that would use this feature. Now that I think about it I'm not sure I see the value that this feature brings compared to just wrapping the token (it's safe to assume that wrappers will always exist for compatibility reasons IMO).

**Comment by bout3fiddy** [comment]
```
Implementing such a functionality would encourage developers to go for this approach more. It's not just about Curve, rebases are a big foot gun in the industry and I think that it is dangerous to "endorse" them.
```
Curve has been a long standing supporter of rebasing markets and it's a pedigree of ours to have rebasing token support in our AMMs. But: I don't disagree. I think rebasing tokens are a small market, and we could revisit them in the future if security around the composability of rebasing tokens improves. 

```
I'm not sure boost is a good name given that we already have a boost concept for the gauges. What about rebalancing donations?
```
Naming rights go to whoever writes the algorithm. We can discuss re-iterate internally.

```
Is it more effective to fully subsidize the rebalancing cost so that LPs earn more fees or should we add these rebalancing donations on top of them?
```
I think we should parameterise them: so a parameter that decides how much of earned revenue from swaps goes into the 'rebalancing funds' which is then used to rebalance?
